[package]
name = "ntcip"
version = "0.1.2"
authors = ["Douglas Lau <doug.lau@state.mn.us>"]
description = "NTCIP: National Transportation Communications for ITS Protocol"
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/ntcip"
repository = "https://github.com/mnit-rtmc/ntcip"
readme = "README.md"
edition = "2018"

[dependencies]
base64 = "0.11"
log = "0.4"
pix = "0.6"
serde = "1.0"
serde_derive = "1.0"
